import logging
from typing import Any, Dict, List

from ddgs import DDGS

# Set up a basic logger so Mohammed (Monitoring) can track errors later
logger = logging.getLogger(__name__)

def search_web(query: str, max_results: int = 5) -> List[Dict[str, Any]]:
    """
    Executes a web search using DuckDuckGo and returns a list of results.
    
    Args:
        query (str): The search term generated by the Research Agent.
        max_results (int): The maximum number of URLs to return.
        
    Returns:
        List[Dict[str, Any]]: A list of dictionaries containing 'title', 'href', and 'body'.
    """
    logger.info(f"Executing web search for query: '{query}'")
    
    try:
        results = []
        with DDGS() as ddgs:
            # text() returns an iterator of dictionaries: {'title': ..., 'href': ..., 'body': ...}
            ddgs_generator = ddgs.text(query, max_results=max_results)
            for result in ddgs_generator:
                results.append({
                    "title": result.get("title", ""),
                    "url": result.get("href", ""),
                    "snippet": result.get("body", "")
                })
                
        logger.info(f"Successfully retrieved {len(results)} results.")
        return results

    except Exception as e:
        logger.error(f"Web search failed for query '{query}': {str(e)}")
        # Return an empty list so the agent knows it failed but doesn't crash the pipeline
        return []

# --- Quick Test Block ---
if __name__ == "__main__":
    test_query = "Latest developments in Multi-Agent AI systems"
    print(f"Testing search for: {test_query}\n")
    
    search_results = search_web(test_query, max_results=3)
    
    for i, res in enumerate(search_results, 1):
        print(f"Result {i}:")
        print(f"Title: {res['title']}")
        print(f"URL: {res['url']}")
        print(f"Snippet: {res['snippet'][:100]}...\n")